### ISSUE TITLE
A background operation called ObservableCollection<point> causes a Call from invalid thread

### ISSUE THREAD

**Issue by xyaoo** [oxyplot/oxyplot-avalonia#33]
UI Binding like this
`			
<oxy:Plot Grid.Row="1" Margin="5">
				<oxy:Plot.Axes>
					<oxy:LinearAxis Title="Value" Position="Right" Minimum="-3" Maximum="3" IsZoomEnabled="False" MajorGridlineStyle="Solid" MinorGridlineStyle="Dot" />
					<oxy:LinearAxis Position="Bottom" MajorGridlineStyle="Dot" MinorGridlineStyle="Dot" />
				</oxy:Plot.Axes>
				<oxy:Plot.Series>
					<oxy:LineSeries Items="{Binding DataSeries}" DataFieldX="Index" DataFieldY="Value" />
				</oxy:Plot.Series>
			</oxy:Plot>
`
define like this
` public ObservableCollection<Point> DataSeries { get; set; } = new ObservableCollection<Point>();`

An exception occurred when i update the value of DataSeries  in the background thread.
In WPF is OK, How do I update UI values in the background thread?

`System.InvalidOperationException: Call from invalid thread
   at Avalonia.Threading.Dispatcher.VerifyAccess() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 48
   at Avalonia.AvaloniaObject.GetValue[T](StyledPropertyBase`1 property) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 251
   at OxyPlot.Avalonia.PlotBase.InvalidatePlot(Boolean updateData) in D:\xyao\Softwares\DNVM\Common\OxyPlot.Avalonia\PlotBase.cs:line 239
   at OxyPlot.Avalonia.Series.OnDataChanged() in D:\xyao\Softwares\DNVM\Common\OxyPlot.Avalonia\Series\Series.cs:line 196
   at OxyPlot.Avalonia.Series.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs notifyCollectionChangedEventArgs) in D:\xyao\Softwares\DNVM\Common\OxyPlot.Avalonia\Series\Series.cs:line 275
   at OxyPlot.Avalonia.Series.EventListener.OnEvent(Object sender, NotifyCollectionChangedEventArgs e) in D:\xyao\Softwares\DNVM\Common\OxyPlot.Avalonia\Series\Series.cs:line 299
   at Avalonia.Utilities.WeakSubscriptionManager.Subscription`1.OnEvent(Object sender, T eventArgs) in /_/src/Avalonia.Base/Utilities/WeakSubscriptionManager.cs:line 184
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at Dnvm.Modules.Sensor.ViewModels.SensorCollectionViewModel.PointUpdate(Int32 sensorId, Point point) in D:\xyao\Softwares\DNVM\Dnvm.Common\Dnvm.Modules\Dnvm.Modules.Sensor\ViewModels\SensorCollectionViewModel.cs:line 74
   at Dnvm.Core.Services.SensorManager.Update(Int32 sensorId, ConnectType connectType, List`1 data) in D:\xyao\Softwares\DNVM\Dnvm.Common\Dnvm.Core\Services\SensorManager.cs:line 178
   at Dnvm.Core.Services.NetworkTCP.TSession.Sampling(MemoryStream ms) in D:\xyao\Softwares\DNVM\Dnvm.Common\Dnvm.Core\Services\NetworkTCP\TSession.cs:line 108
   at Dnvm.Core.Services.NetworkTCP.TSession.OnRead(Int64 channelId, MemoryStream memoryStream) in D:\xyao\Softwares\DNVM\Dnvm.Common\Dnvm.Core\Services\NetworkTCP\TSession.cs:line 56
   at Dnvm.Core.Services.NetworkTCP.TSessionManager.OnRead(Int64 channelId, MemoryStream memoryStream) in D:\xyao\Softwares\DNVM\Dnvm.Common\Dnvm.Core\Services\NetworkTCP\TSessionManager.cs:line 64
   at Dnvm.Core.IServices.Network.AService.OnRead(Int64 channelId, MemoryStream memoryStream) in D:\xyao\Softwares\DNVM\Dnvm.Common\Dnvm.Core\IServices\Network\AService.cs:line 72
   at Dnvm.Core.Services.NetworkTCP.TChannel.OnRead(MemoryStream memoryStream) in D:\xyao\Softwares\DNVM\Dnvm.Common\Dnvm.Core\Services\NetworkTCP\TChannel.cs:line 390`

**Comment by VisualMelon** [comment]
Looks like it is crashing when it is checking the size of the control on line https://github.com/oxyplot/oxyplot-avalonia/blob/master/Source/OxyPlot.Avalonia/PlotBase.cs#L239

I'm not sure why this check is there, but it should be done on the UI thread if at all.

As an initial test, you could try overriding `PlotView.InvalidatePlot` and have it call the base-method on the UI thread, to check whether this stops it crashing.

**Comment by kekekeks** [comment]
We don't support data updates from non-UI thread. Marshal those manually via `Dispatcher.UIThread.Invoke(() => ...)`

**Comment by VisualMelon** [comment]
@kekekeks I think it's the `Width` and `Height` calls that are crashing, since they check for the UI thread also

**Comment by VisualMelon** [comment]
OK, I've got in a bit of a muddle, but there are two issues here:

1. There are bugs with the Oxyplot.Avalonia plot view that make it inconsistent with e.g. WPF wrt. invalidating the plot (i.e. it should re-direct you to the right thread). This is an issue when using a normal combination of `PlotModel` and `PlotView`, and while revealed by the OP can't provide a solution.

    Line https://github.com/oxyplot/oxyplot-avalonia/blob/526760ddf4702a4f96708d39d97531d0e2e6f185/Source/OxyPlot.Avalonia/PlotBase.cs#L528 looks wrong and doesn't match WPF: would also cause crashes. I don't understand the comment on `InvalidatePlot` about not blocking the UI thread, but it's C&P'd from the WPF provision.

    I'm testing fixing the above, and moving the bounds checks and UI calls into a separate method that is invoked on the UI thread asynchronously. This doesn't seem to behave ideally: you can easily lock up the UI by calling `InvalidatePlot` too often. I'm a bit surprised by this, because I do something similar in one of my own projects (invoking `InvalidePlot` as @kekekeks describes) many times a second and never had issues with it locking up, but I suppose it makes sense (not sure what, if anything, we should do about that).

2. Using the `Plot` XAML provision as in the OP, you must (as @kekekeks said) perform data-updates on the UI thread. You probably can override `Plot.InvaliatePlot` to call onto the UI thread for you so the rebuilding of the plot model occurs on the UI thread, but then you still need to serialise the data-update itself with respect to updating the plotmodel, so that isn't feasible.

@xyaoo you have to synchronise your data-updates onto the UI thread as @kekekeks said (per 2), the bugs (per 1) shouldn't affect you if you do this; ignore my first comment, it will only set you up for a different set of thread related crashes.

**Comment by xyaoo** [comment]
Thank you for your(@VisualMelon ) answer.
Now. I'm creating a DispatcherTimer in UI thread and calling 'InvalidatePlot' per 100ms. And creating 'PlotModel'.
When the data is updated in the background, the 'Points' in 'PlotModel.Series' is added. 
This seems to be working fine, But sometimes it produces unusual information on the chart.I think it changed the collection in the background while the UI was rendering.
![无标题](https://user-images.githubusercontent.com/34727649/122530469-14832700-d051-11eb-8095-84a9a50de612.png)
What can be done to reduce this?

**Comment by VisualMelon** [comment]
This is the concurrent modification exception I was talking about: if the chart is updating or rendering then you can't modify the entries in the plotmodel. See https://github.com/oxyplot/oxyplot/issues/1482 on the core repo.

Basically you need to `lock (PlotModel.SyncRoot)` if you are modifying the contents of the `PlotModel` on a separate thread: this serialises data updates with plot and render updates (`InvalidatePlot` takes the lock internally).
