### ISSUE TITLE
The previewer process exited unexpectedly - No rendering system configured 

### ISSUE THREAD

**Issue by rehakmatej** [oxyplot/oxyplot-avalonia#69]
Hello everyone. I have a problem with using of Oxyplot.Avalonia. The previewer is not able to render the window defined in .axaml file. This happens in original solution downloaded from this repository while the whole solution is able to build and run. I set the SimpleDemo as a startup project, built them and tried to run them and everything works correctly. Next when I open MainWindow.axaml the previewer shows error message. Below is the output from Avalonia Diagnostics. I tried to delete bin and obj folders and build the project again, but it did not help. 

Next I have created my own project with OxyPlot.Avalonia and same thing happens. I thought that this is problem of AvaloniaUI, so I decided to download samples from AvaloniaUI repo, tried to run them and the previewer works correctly.

The most interesting thing is exception message "No rendering system configured", so my question is how to avoid this exception?

Thank you

08:34:02.004 [Information] 0 Starting previewer process for '"C:\Users\rehakmatej\Downloads\oxyplot-avalonia-master\oxyplot-avalonia-master\Source\Examples\Avalonia\SimpleDemo\bin\Debug\net7.0\SimpleDemo.dll"'
08:34:02.004 [Debug] 0 > dotnet.exe "exec --runtimeconfig \"C:\Users\rehakmatej\Downloads\oxyplot-avalonia-master\oxyplot-avalonia-master\Source\Examples\Avalonia\SimpleDemo\bin\Debug\net7.0\SimpleDemo.runtimeconfig.json\" --depsfile \"C:\Users\rehakmatej\Downloads\oxyplot-avalonia-master\oxyplot-avalonia-master\Source\Examples\Avalonia\SimpleDemo\bin\Debug\net7.0\SimpleDemo.deps.json\" \"C:\Users\rehakmatej\.nuget\packages\avalonia\11.0.0\buildTransitive\\..\tools\netcoreapp2.0\designer\Avalonia.Designer.HostApp.dll\" --transport tcp-bson://127.0.0.1:51907/ \"C:\Users\rehakmatej\Downloads\oxyplot-avalonia-master\oxyplot-avalonia-master\Source\Examples\Avalonia\SimpleDemo\bin\Debug\net7.0\SimpleDemo.dll\""
08:34:02.011 [Information] 18596 Started previewer process for '"C:\Users\rehakmatej\Downloads\oxyplot-avalonia-master\oxyplot-avalonia-master\Source\Examples\Avalonia\SimpleDemo\bin\Debug\net7.0\SimpleDemo.dll"'. Waiting for connection to be initialized.
08:34:02.227 [Information] 18596 Connection initialized
08:34:02.228 [Debug] 18596 => Sending ClientSupportedPixelFormatsMessage { Formats: [Bgra8888, Rgba8888] }
08:34:02.229 [Debug] 18596 => Sending ClientRenderInfoMessage { DpiX: 96, DpiY: 96 }
08:34:02.230 [Debug] 18596 => Sending UpdateXamlMessage { Xaml: "<Window x:Class=\"SimpleDemo.Mai…", AssemblyPath: "C:\Users\rehakmatej\Downloads\o…", XamlFileProjectPath: null }
08:34:02.249 [Debug] 18596 <= "Obtaining AppBuilder instance from SimpleDemo.App"
08:34:02.263 [Debug] 18596 <= "Initializing application in design mode"
08:34:02.303 [Error] 18596 <= "Unhandled exception. System.InvalidOperationException: No rendering system configured."
08:34:02.305 [Error] 18596 <= "   at Avalonia.AppBuilder.Setup() in /_/src/Avalonia.Controls/AppBuilder.cs:line 289"
08:34:02.306 [Error] 18596 <= "   at Avalonia.AppBuilder.SetupWithoutStarting() in /_/src/Avalonia.Controls/AppBuilder.cs:line 175"
08:34:02.307 [Error] 18596 <= "   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.AppInitializer.ConfigureApp(IAvaloniaRemoteTransportConnection transport, CommandLineArgs args, Object obj) in /_/src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs:line 154"
08:34:02.307 [Error] 18596 <= "   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.Main(String[] cmdline) in /_/src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs:line 185"
08:34:02.308 [Error] 18596 <= "   at Avalonia.Designer.HostApp.Program.Main(String[] args) in /_/src/tools/Avalonia.Designer.HostApp/Program.cs:line 47"
08:34:04.605 [Information]  Process exited
08:34:04.606 [Information]  Stopping previewer process
08:34:04.605 [Error]  Connection error
System.IO.IOException: Unable to read data from the transport connection: Stávající připojení bylo vynuceně ukončeno vzdáleným hostitelem. ---> System.Net.Sockets.SocketException: Stávající připojení bylo vynuceně ukončeno vzdáleným hostitelem
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.<ReadExact>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.<Reader>d__16.MoveNext()

**Comment by DCTewi** [comment]
I just ran into this issue as well.

According to #58, nuget consider `2.1.0` is newer than `2.1.0-Avalonia11`. You need to use the latest version of the repo as a subproject or manually select the version as `2.1.0-Avalonia11` on nuget. 

![image](https://github.com/user-attachments/assets/e3de1e51-91dc-4727-8332-08253f805598)
